Feat/navbar
MisterAzix/hetic-leboncoin-symfony pull request #26
Opened 2022-10-25 14:49 UTC by Triips-TheCoder

# Ticket Notion

# Screen (si besoin)

# Autre information

2022-10-25 15:17 UTC, MisterAzix submitted a review, later dismissed

2022-10-26 07:32 UTC, justinDev91 approved these changes

2022-10-26 07:44 UTC, MisterAzix approved these changes

2022-10-26 07:44 UTC, merged

2022-10-26 07:56 UTC, PatRider64 requested changes

2022-10-26 07:56 UTC, PatRider64 commented on src/templates/base.html.twig
> +        </li>
```suggestion
         {% if is_granted('ROLE_USER') %}
         <li class="mb-2">
            <a href="#" class="fs-2">+ Déposer une annonce</a>
        </li>
        {% endif %}
```

2022-10-26 07:56 UTC, PatRider64 commented on src/templates/base.html.twig
> +        </li>
```suggestion
        {% if is_granted('ROLE_USER') %}
        <li class="mb-2">
            <a href='#' class="fs-2">Se déconnecter</a>
         {% else % }  
        <li class="mb-2">
            <a href="#" class="fs-2">S'inscrire</a>
        </li>
        <li class="mb-2">
            <a href="#" class="fs-2">Se connecter</a>
        </li>
        {% endif %}
```

2022-10-26 07:56 UTC, PatRider64 commented on src/templates/partials/navbar.html.twig
> +                annonce</a>
```suggestion
            {% if is_granted('ROLE_USER') %}
            <a class='font-normal font-medium d-sm-none d-md-inline hide-on-mobile' href="#">+ déposer une
                annonce</a>
            {% endif %}    
```

2022-10-26 07:56 UTC, PatRider64 commented on src/templates/partials/navbar.html.twig
> +        </li>
```suggestion
            {% if is_granted('ROLE_USER') %}
            <a class='font-normal d-sm-none d-md-inline hide-on-mobile' href="#">Se déconnecter</a>
            {% else %}
            <a class='font-normal pe-4 d-sm-none d-md-inline hide-on-mobile' href="#">S'inscrire</a>
            <a class='font-normal d-sm-none d-md-inline hide-on-mobile' href="#">Se connecter</a>
         {% endif %}
        </li>
```