Feat(back) : full factory and appfixture
MisterAzix/hetic-leboncoin-symfony pull request #48
Opened 2022-10-27 14:23 UTC by justinDev91

# Ticket Notion
Full entity factory and appfixtures

# Screen (si besoin)

# Autre information

2022-10-27 18:18 UTC, PatRider64 approved these changes

2022-10-27 21:51 UTC, MisterAzix requested changes
Good, but change all `tag_controllee` by `tag`

2022-10-27 21:51 UTC, MisterAzix commented on src/src/Controller/TagControlleeController.php
> +#[Route('/tag/controllee')]
```suggestion
#[Route('/tag')]
```

2022-10-27 21:51 UTC, MisterAzix commented on src/src/Controller/TagControlleeController.php
> +class TagControlleeController extends AbstractController
```suggestion
class TagController extends AbstractController
```

2022-10-28 07:11 UTC, justinDev91 commented on src/src/Controller/TagControlleeController.php
> +#[Route('/tag/controllee')]
Bien vu

2022-10-28 11:41 UTC, MisterAzix approved these changes

2022-10-28 11:41 UTC, merged